
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.analizadorInstrucciones;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int POR = 7;
  public static final int EOF = 0;
  public static final int PARENTESIS_CERRADO = 10;
  public static final int MAS = 5;
  public static final int NUMERO = 3;
  public static final int DIV = 8;
  public static final int IGUAL = 4;
  public static final int error = 1;
  public static final int PARENTESIS_ABIERTO = 9;
  public static final int IDENTIFICADOR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "NUMERO",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO"
  };
}

